### ISSUE TITLE
Move post type support calls into a function

### ISSUE THREAD

**Issue by GaryJones** [bradpotter/microdata-manager#5]
``` php
add_post_type_support( 'post', array( 'microdata-manager' ) );
add_post_type_support( 'page', array( 'microdata-manager' ) );
```

These are in the global scope and called when the functions file gets included, currently at `genesis_init`. It would be good if these were in a function themselves, so that they could potentially be unhooked, should someone want the functionality of the plugin, but not for posts and pages.

**Comment by bradpotter** [comment]
Move post type support calls into a function. Had to specify priority for it to work properly. Not sure of priority choice. https://github.com/bradpotter/microdata-manager/commit/aa2600885f53ab6aae7bead11081627d0ad78f45

**Comment by GaryJones** [comment]
Instead of hooking to `genesis_init` for anything, hook to `genesis_setup` instead. The priority may still be needed, as you're only requiring the file at that hook and default priority.

**Comment by bradpotter** [comment]
Hooked to genesis_setup. Priority setting was not necessary.
